# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EasyBrowser.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1115, 811)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.labelType = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelType.setFont(font)
        self.labelType.setObjectName("labelType")
        self.gridLayout.addWidget(self.labelType, 0, 0, 1, 1)
        self.lineEditUrl = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditUrl.setFont(font)
        self.lineEditUrl.setInputMethodHints(QtCore.Qt.ImhUrlCharactersOnly)
        self.lineEditUrl.setObjectName("lineEditUrl")
        self.gridLayout.addWidget(self.lineEditUrl, 0, 1, 1, 6)
        self.pushButtonGo = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonGo.setFont(font)
        self.pushButtonGo.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.pushButtonGo.setAutoDefault(True)
        self.pushButtonGo.setDefault(True)
        self.pushButtonGo.setObjectName("pushButtonGo")
        self.gridLayout.addWidget(self.pushButtonGo, 0, 7, 1, 1)
        self.pushButtonGoBack = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonGoBack.setStyleSheet("background-color: rgb(57, 188, 200);")
        self.pushButtonGoBack.setObjectName("pushButtonGoBack")
        self.gridLayout.addWidget(self.pushButtonGoBack, 1, 0, 1, 2)
        self.pushButtonGoForward = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonGoForward.setStyleSheet("background-color: rgb(57, 188, 200);")
        self.pushButtonGoForward.setObjectName("pushButtonGoForward")
        self.gridLayout.addWidget(self.pushButtonGoForward, 1, 2, 1, 1)
        self.pushButtonZoom = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonZoom.setStyleSheet("background-color: rgb(170, 0, 255);")
        self.pushButtonZoom.setObjectName("pushButtonZoom")
        self.gridLayout.addWidget(self.pushButtonZoom, 1, 3, 1, 1)
        self.pushButtonZoomOut = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonZoomOut.setStyleSheet("background-color: rgb(170, 0, 255);")
        self.pushButtonZoomOut.setObjectName("pushButtonZoomOut")
        self.gridLayout.addWidget(self.pushButtonZoomOut, 1, 4, 1, 1)
        self.pushButtonStop = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonStop.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.pushButtonStop.setObjectName("pushButtonStop")
        self.gridLayout.addWidget(self.pushButtonStop, 1, 5, 1, 1)
        self.pushButtonReload = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonReload.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.pushButtonReload.setObjectName("pushButtonReload")
        self.gridLayout.addWidget(self.pushButtonReload, 1, 6, 1, 2)
        self.widgetBrowse = QWebEngineView(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.widgetBrowse.setFont(font)
        self.widgetBrowse.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.widgetBrowse.setFocusPolicy(QtCore.Qt.NoFocus)
        self.widgetBrowse.setStyleSheet("background-color: rgb(200, 199, 200);")
        self.widgetBrowse.setObjectName("widgetBrowse")
        self.gridLayout.addWidget(self.widgetBrowse, 2, 0, 1, 8)
        self.labelType.raise_()
        self.lineEditUrl.raise_()
        self.widgetBrowse.raise_()
        self.pushButtonGo.raise_()
        self.pushButtonGoBack.raise_()
        self.pushButtonStop.raise_()
        self.pushButtonZoomOut.raise_()
        self.pushButtonGoForward.raise_()
        self.pushButtonReload.raise_()
        self.pushButtonZoom.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1115, 31))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuBrowser = QtWidgets.QMenu(self.menubar)
        self.menuBrowser.setObjectName("menuBrowser")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSaveAs = QtWidgets.QAction(MainWindow)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionPrint = QtWidgets.QAction(MainWindow)
        self.actionPrint.setObjectName("actionPrint")
        self.actionPrint_Preview = QtWidgets.QAction(MainWindow)
        self.actionPrint_Preview.setObjectName("actionPrint_Preview")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionFont = QtWidgets.QAction(MainWindow)
        self.actionFont.setObjectName("actionFont")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionCut = QtWidgets.QAction(MainWindow)
        self.actionCut.setObjectName("actionCut")
        self.actionZoom = QtWidgets.QAction(MainWindow)
        self.actionZoom.setObjectName("actionZoom")
        self.actionZoom_Out = QtWidgets.QAction(MainWindow)
        self.actionZoom_Out.setObjectName("actionZoom_Out")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionReload = QtWidgets.QAction(MainWindow)
        self.actionReload.setObjectName("actionReload")
        self.actionStop = QtWidgets.QAction(MainWindow)
        self.actionStop.setObjectName("actionStop")
        self.actionGo_Back = QtWidgets.QAction(MainWindow)
        self.actionGo_Back.setObjectName("actionGo_Back")
        self.actionGo_Forward = QtWidgets.QAction(MainWindow)
        self.actionGo_Forward.setObjectName("actionGo_Forward")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSaveAs)
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addAction(self.actionPrint_Preview)
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionFont)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionZoom)
        self.menuEdit.addAction(self.actionZoom_Out)
        self.menuHelp.addAction(self.actionAbout)
        self.menuBrowser.addAction(self.actionReload)
        self.menuBrowser.addAction(self.actionStop)
        self.menuBrowser.addAction(self.actionGo_Back)
        self.menuBrowser.addAction(self.actionGo_Forward)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuBrowser.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EasyBrowser"))
        self.labelType.setText(_translate("MainWindow", "Type Url Here"))
        self.pushButtonGo.setText(_translate("MainWindow", "GO"))
        self.pushButtonGoBack.setText(_translate("MainWindow", "Back"))
        self.pushButtonGoForward.setText(_translate("MainWindow", "Forward"))
        self.pushButtonZoom.setText(_translate("MainWindow", "Zoom"))
        self.pushButtonZoomOut.setText(_translate("MainWindow", "Zoom Out"))
        self.pushButtonStop.setText(_translate("MainWindow", "Stop"))
        self.pushButtonReload.setText(_translate("MainWindow", "Reload"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuBrowser.setTitle(_translate("MainWindow", "Browser"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSaveAs.setText(_translate("MainWindow", "Save As"))
        self.actionPrint.setText(_translate("MainWindow", "Print"))
        self.actionPrint_Preview.setText(_translate("MainWindow", "Print Preview"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionFont.setText(_translate("MainWindow", "Font"))
        self.actionCopy.setText(_translate("MainWindow", "Copy"))
        self.actionCut.setText(_translate("MainWindow", "Cut"))
        self.actionZoom.setText(_translate("MainWindow", "Zoom"))
        self.actionZoom_Out.setText(_translate("MainWindow", "Zoom Out"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionReload.setText(_translate("MainWindow", "Reload"))
        self.actionStop.setText(_translate("MainWindow", "Stop"))
        self.actionGo_Back.setText(_translate("MainWindow", "Go Back"))
        self.actionGo_Forward.setText(_translate("MainWindow", "Go Forward"))

from PyQt5.QtWebEngineWidgets import QWebEngineView
